### ISSUE TITLE
Could not find module 'SwiftUIX' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by SapaTech** [SwiftUIX/SwiftUIX#245]
Hi, automatic app preview not working with SwiftUIX, can someone help me please)

**Comment by vmanot** [comment]
@SapaTech hey - this is an Xcode bug. Cleaning derived data should fix it, but if not then it's something you should report to Apple.

**Comment by liseami** [comment]
xCode has already resolved this issue. Similarly, other packages such as Pow have resolved this problem as an SPM package. However, SwiftUIx still encounters this problem during preview.

**Comment by vmanot** [comment]
@liseami do you know why it may be occurring/what the fix is? Happy to make the required changes, I'm just not sure how to repro it.

**Comment by liuyongjiesail** [comment]
same problem, have anyone resolved this problem?

**Comment by vmanot** [comment]
@liuyongjiesail give me a repro.
