### ISSUE TITLE
SearchBar: click the 'cancel' button and view will close

### ISSUE THREAD

**Issue by github-gxxx** [SwiftUIX/SwiftUIX#253]
sample repo:
https://github.com/github-gxxx/swiftUIX_SearchBarTest

**Comment by vmanot** [comment]
@github-gxxx thank you for taking out the time and effort to demo it! I've fixed it now.

**Comment by zane-carter** [comment]
I'm still experiencing this issue on iOS 14.5.1 (Real Device) compiled with Xcode 12.5

**Comment by zane-carter** [comment]
Package Version 0.0.6

**Comment by vmanot** [comment]
@zane-carter this is fixed on `master`, I'll be cutting out a new release soon.

**Comment by zane-carter** [comment]
Thanks @vmanot.
