### ISSUE TITLE
'hoverEffect' is only available in iOS 13.4 or newer

### ISSUE THREAD

**Issue by skywalkerlw** [SwiftUIX/SwiftUIX#330]
Happened on Xcode 13.2 beta 2

![image](https://user-images.githubusercontent.com/2090084/144143514-a396723f-cc9d-4f88-8a8d-f9379df1496f.png)

**Comment by Brett-Best** [comment]
I’m not seeing this locally or in the github actions CI, can you provide the full build log?

**Comment by vmanot** [comment]
@skywalkerlw I'm not seeing this either, and the availability condition should not be causing that. Please reopen if this persists, and it'd be great if you could attach steps or better yet an example project with the compilation issue.

**Comment by skywalkerlw** [comment]
This only happens on Xcode 13.2 beta2

![image](https://user-images.githubusercontent.com/2090084/144739308-203cf3b7-836c-48a8-bea9-2ed5e517ada0.png)

This is the demo i created followed by Xcode template and only SwiftUIX is dependent. https://github.com/skywalkerlw/SwiftUIXSpike

**Comment by Brett-Best** [comment]
I can reproduce, a workaround for me was to change to building for release instead of debug. Could you file a feedback for this with Apple? Seems like a bug to me, will check again when new beta or RC of Xcode 13.2 comes out.

**Comment by skywalkerlw** [comment]
still happens on Xcode 13.2 RC

**Comment by vmanot** [comment]
@skywalkerlw yeah, I've patched it for now. If you need that code, just copy paste it - but otherwise it's disabled until Xcode decides to get its shit together.

**Comment by vmanot** [comment]
@skywalkerlw this is now fixed thanks to @Brett-Best, who correctly noted it's `@inlinable` that's causing an issue. Still marked as an `apple-bug` because it's a bug with Swift inlining, but it's back and available again!

**Comment by skywalkerlw** [comment]
Thank you :)

**Comment by SwapnanilDhol** [comment]
Hey, @vmanot. Looks like this problem has resurfaced with Xcode 13.2.1. I am on the master branch of this package, have restarted Xcode, my Mac, cleaned derived data but this issue still seems to persist. Is this something that you're aware of?  

 ![Screenshot 2021-12-22 at 10 32 40 PM](https://user-images.githubusercontent.com/41509261/147128877-17e61712-1735-4232-a463-2b3984f2fb0d.png)
