### ISSUE TITLE
Support for VisionOS (xrOS)

### ISSUE THREAD

**Issue by pgorrindo** [SwiftUIX/SwiftUIX#436]
Although there was recently [this commit to fix compilation for xrOS](https://github.com/SwiftUIX/SwiftUIX/commit/22dbeca824b79bf783a49d6b0fc8dd67f8e8c04c), as of yesterday on Xcode 15.0-beta3 with SwiftUIX v0.1.5, I'm getting a number of `... is unavailable in visionOS` errors. Perhaps some `#if !os(visionOS)` checks might still be needed?

<img width="333" alt="swiftuix-2023-07-11" src="https://github.com/SwiftUIX/SwiftUIX/assets/366337/8c241ffe-0614-4f7c-b1cc-3bec114682b5">

**Comment by vmanot** [comment]
@pgorrindo thanks for raising the issue - this should be fixed on `0.1.6`.

**Comment by pgorrindo** [comment]
thanks @vmanot for the quick turnaround! unfortunately, I'm still seeing these buildtime issues with `0.1.6`. Both on Xcode 15-b3, and I just checked beta 4 for good measure.

**Comment by vmanot** [comment]
@pgorrindo that's odd - I'm able to build on Xcode 15b3. Let me re-check this today.

**Comment by vmanot** [comment]
@pgorrindo could you try cloning the repo fresh and building for the Vision Pro simulator? It seems to be building fine for me.

<img width="1512" alt="Screenshot 2023-07-15 at 1 04 57 PM" src="https://github.com/SwiftUIX/SwiftUIX/assets/5306992/74b5a094-7a45-489d-91fd-6b8fb2612f45">

**Comment by pgorrindo** [comment]
> @pgorrindo could you try cloning the repo fresh and building for the Vision Pro simulator? It seems to be building fine for me.

@vmanot thanks for your persistence! I've tried everything I can think of, in various permutations, on both Xcode 15-b3 and -b4:
- cleaned the build and DerivedData folders
- removed `org.swift.swiftpm` in `~/Library/Caches`
- removed SwiftUIX as a dependency and then re-added
- File > Packages > Reset Package Caches
- tried a variant of this [xcode cleaning shell script](https://gist.github.com/arthurdapaz/e2a4fc83fa561ec52af83a5b08d0497d)

But no luck -- I still get the same SwiftUIX buildtime errors.

Of note, I'm using the Firebase SDK in my Xcode project, which to support VisionOS under the current version, requires [running Xcode with an `env` variable](https://firebase.google.com/support/release-notes/ios#cloud-firestore) (`FIREBASE_SOURCE_FIRESTORE`) -- but I don't think (?) this would have an effect on SwiftUIX, no?

**Comment by vmanot** [comment]
@pgorrindo I don't think that should have an effect. Could you just try building SwiftUIX alone (just the SwiftUIX SPM package, cloned from GitHub, _outside_ your workspace/project) and confirm whether you're still encountering the errors? And if so could you post another screenshot - I'd like to see if the errors are the same.

**Comment by pgorrindo** [comment]
@vmanot ok, gotcha. Well when I build SwiftUIX stand-alone for VisionOS, I don't get those buildtime errors and SwiftUIX compiles successfully. So then it must be something specific to my Xcode project?

**Comment by vmanot** [comment]
@pgorrindo yeah I think it's something specific to your setup. I'd recommend manually going over the files changed in the latest commit + comparing them with the version of SwiftUIX that you have in your Xcode project to confirm whether it's outdated.
