### ISSUE TITLE
Multiple warnings with Xcode 15.0.1

### ISSUE THREAD

**Issue by hyouuu** [SwiftUIX/SwiftUIX#454]
`Generic parameter 'Value' shadows generic parameter from outer scope with the same name; this is an error in Swift 6`
<img width="320" alt="Screenshot 2023-10-29 at 2 44 12 PM" src="https://github.com/SwiftUIX/SwiftUIX/assets/5061867/e8a16df7-5d86-486d-b32a-2e0e0931db36">

**Comment by vmanot** [comment]
@hyouuu I just released 0.1.8 which should fix this.

**Comment by hyouuu** [comment]
@vmanot Thanks for the quick reply, but which commit fixed them? I just updated but still see this:
<img width="328" alt="Screenshot 2023-10-30 at 1 10 23 AM" src="https://github.com/SwiftUIX/SwiftUIX/assets/5061867/4c041fb1-0c0c-43cc-9cbb-2c322070ac2b">

**Comment by vmanot** [comment]
@hyouuu are you sure you're on the latest release and not pinned to an older one? Can you dump `AnyForEach` from your Xcode's checkout of SwiftUIX in a gist to confirm?

**Comment by hyouuu** [comment]
@vmanot I'm using `main` which has this:

```
{
        "package": "SwipeActions",
        "repositoryURL": "https://github.com/aheze/SwipeActions",
        "state": {
          "branch": "main",
          "revision": "2880393b349491100146c73831325f955bbf54c5",
          "version": null
        }
      }
```
